export enum RuleId {
  ChooseSpecialActionTile = 1,
  PlaceTokenOnCabaret,
  PlaceTokenOnCabaretOnStarCase,
  PlaceTokenOnCabaretNearToOther,
  PlaceTokenOnCabaretNearToLast,
  ChooseAction,
  AdvanceInFinanceCenter,
  ChooseIfAdvanceInFinanceCenterOrNot,
  PlaceTokenOnRaceTrack,
  PlaceTokenOnRaceTrackAnywhere,
  PlaceTokenOnAnotherRaceTrack,
  SwitchInfluenceTokens,
  PlaceTokenOnCabaretOrRaceTrack,
  TakeThreeSpecialActionTilesAndChooseOne,
  PlaceTokenOnSameRaceTrack,
  ShowTwoCharacterTiles,
  ReplaceCharacterTiles,
  ChooseActionForOpponent,
  GetCharacterTiles
}
